# Generated by cpp4r: do not edit by hand

#' @title TVP-VAR Estimation with Stochastic Volatility (Baumeister-Peersman)
#' @description Estimates a Time-Varying Parameter VAR with stochastic volatility
#'   following Baumeister and Peersman (2013) / Primiceri (2005). Uses MCMC
#'   (Gibbs sampling with Metropolis-Hastings steps) for estimation.
#' @param y Time series matrix (T x N). For benchmark specification, use log
#'   differences of oil production, real oil price, and world industrial
#' production.
#' @param L Lag order (default 4 for quarterly data).
#' @param training_years Years for training sample (25 for benchmark, 5 for Kilian
#' spec).
#' @param n_burn Number of burn-in iterations (default 50000).
#' @param n_draws Number of draws to keep from Gibbs sampler (default 500).
#' @param thinning Thinning interval - save every D-th draw (default 10).
#' @param stability_constraint Whether to impose VAR stability (0 = no, 1 = yes).
#' @param lambda_param Time variation parameter. Use 0.0001 for "Small"
#' (Primiceri), 0.01 for "Large" (most variation), or 0.00035 for Cogley-Sargent.
#' @param first_diff Whether data is in first differences (1 = yes for benchmark).
#' @return A list containing:
#'   \describe{
#'     \item{SD}{List of state draws (time-varying VAR coefficients)}
#'     \item{QD}{List of state innovation covariance matrix draws}
#'     \item{VD}{Matrix of volatility innovation standard deviations}
#'     \item{OM}{List of stochastic volatility draws}
#'     \item{AA}{List of off-diagonal A(t) element draws}
#'     \item{S1}{Scalar covariance for first block of A innovations}
#'     \item{S2}{List of covariance matrices for second block of A innovations}
#'     \item{n_saved}{Number of draws saved}
#'     \item{T_eff}{Effective sample size}
#'     \item{N}{Number of variables}
#'     \item{L}{Lag order}
#'   }
#' @export
tvp_var_estimate <- function(y, L, training_years, n_burn, n_draws, thinning, stability_constraint, lambda_param, first_diff) {
	.Call(`_bp13_tvp_var_estimate`, y, L, training_years, n_burn, n_draws, thinning, stability_constraint, lambda_param, first_diff)
}

#' @title Compute TVP-VAR Impulse Responses with Sign Restrictions
#' @description Computes generalized impulse response functions for a TVP-VAR
#'   with sign restrictions, following Baumeister and Peersman (2013).
#'   Identifies three structural shocks: oil supply, oil-specific demand, and
#'   global demand (aggregate activity) shocks.
#' @param tvp_result Output from tvp_var_estimate.
#' @param y Original data matrix (T x N).
#' @param L Lag order (must match tvp_var_estimate).
#' @param training_years Years for training sample (must match tvp_var_estimate).
#' @param irf_horizon IRF horizon in periods (default 21 = 5 years + 1).
#' @param n_reps Number of sign-restriction draws per time period (default 500).
#' @param h_restrict Number of periods sign restrictions must hold (default 1).
#' @param first_diff Whether data is in first differences (1 = yes).
#' @return A list containing:
#'   \describe{
#'     \item{IRF_supply}{Array of supply shock IRFs (HOR x N x T)}
#'     \item{IRF_demand}{Array of oil-specific demand shock IRFs}
#'     \item{IRF_global}{Array of global demand shock IRFs}
#'     \item{slope_S_D}{Supply elasticities over time}
#'     \item{slope_S_A}{Supply elasticities (global shock identification)}
#'     \item{slope_D_D}{Demand elasticities over time}
#'     \item{irf_horizon}{IRF horizon used}
#'     \item{T_eff}{Effective sample size}
#'   }
#' @export
tvp_var_irfs <- function(tvp_result, y, L, training_years, irf_horizon, n_reps, h_restrict, first_diff) {
	.Call(`_bp13_tvp_var_irfs`, tvp_result, y, L, training_years, irf_horizon, n_reps, h_restrict, first_diff)
}

#' @title Compute Time-Varying Elasticities
#' @description Computes time-varying oil supply and demand elasticities
#'   following Baumeister and Peersman (2013), Figure 2.
#' @param tvp_result Output from tvp_var_estimate.
#' @param y Original data matrix (T x N).
#' @param L Lag order.
#' @param training_years Years for training sample.
#' @param n_reps Number of draws per time period (default 500).
#' @param h_restrict Number of periods sign restrictions must hold (default 1).
#' @param first_diff Whether data is in first differences (1 = yes).
#' @param upper_supply Upper bound on supply elasticity (default 0.6).
#' @param lower_demand Lower bound on demand elasticity (default -0.8).
#' @return A list containing elasticity distributions over time.
#' @export
tvp_var_elasticities <- function(tvp_result, y, L, training_years, n_reps, h_restrict, first_diff, upper_supply, lower_demand) {
	.Call(`_bp13_tvp_var_elasticities`, tvp_result, y, L, training_years, n_reps, h_restrict, first_diff, upper_supply, lower_demand)
}

#' @title Compute Figure 2: Time-Varying Impact IRFs
#' @description Computes time-varying impact impulse responses for oil supply,
#'   oil-specific demand, and aggregate demand shocks, with elasticity bounds.
#'   Following Baumeister and Peersman (2013), Figure 2.
#' @param tvp_result Output from tvp_var_estimate.
#' @param y Original data matrix (T x N).
#' @param L Lag order.
#' @param n_reps Number of sign-restriction draws per time period (default 500).
#' @param h_restrict Number of periods sign restrictions must hold (default 1).
#' @param first_diff Whether data is in first differences (1 = yes).
#' @param upper_supply Upper bound on supply elasticity (default 0.6).
#' @param lower_demand Lower bound on demand elasticity (default -0.8).
#' @param start_period Starting period for output (default 4 for 1974Q1).
#' @return A list containing matrices for each shock-variable combination.
#'   Each matrix is n_time x 7 with columns: median, p025, p975, p16, p84, max,
#' min.
#' @export
tvp_var_figure2 <- function(tvp_result, y, L, n_reps, h_restrict, first_diff, upper_supply, lower_demand, start_period) {
	.Call(`_bp13_tvp_var_figure2`, tvp_result, y, L, n_reps, h_restrict, first_diff, upper_supply, lower_demand, start_period)
}

#' @title Compute Figure 3: Persistence of Oil Price Inflation
#' @description Computes time-varying persistence of real oil price inflation
#'   using spectral density at frequency zero. Following Baumeister and
#'   Peersman (2013), Figure 3.
#' @param tvp_result Output from tvp_var_estimate.
#' @param n_freq Not used (for compatibility).
#' @param price_var Index of price variable (default 2, 1-indexed for R).
#' @return A list containing persistence measures over time with percentiles.
#' @export
tvp_var_figure3 <- function(tvp_result, n_freq, price_var) {
	.Call(`_bp13_tvp_var_figure3`, tvp_result, n_freq, price_var)
}

#' @title Compute Figure 4: Time-Varying Elasticities
#' @description Computes time-varying oil supply and demand elasticities
#'   with elasticity bounds. Following Baumeister and Peersman (2013), Figure 4.
#' @param tvp_result Output from tvp_var_estimate.
#' @param y Original data matrix (T x N).
#' @param L Lag order.
#' @param n_reps Number of sign-restriction draws per time period (default 500).
#' @param h_restrict Number of periods sign restrictions must hold (default 1).
#' @param first_diff Whether data is in first differences (1 = yes).
#' @param upper_supply Upper bound on supply elasticity (default 0.6).
#' @param lower_demand Lower bound on demand elasticity (default -0.8).
#' @param start_period Starting period for output (default 4 for 1974Q1).
#' @return A list containing elasticity matrices over time.
#'   Each matrix is n_time x 7 with columns: median, p025, p975, p16, p84, max, min.
#' @export
tvp_var_figure4 <- function(tvp_result, y, L, n_reps, h_restrict, first_diff, upper_supply, lower_demand, start_period) {
	.Call(`_bp13_tvp_var_figure4`, tvp_result, y, L, n_reps, h_restrict, first_diff, upper_supply, lower_demand, start_period)
}
