// Generated by cpp4r: do not edit by hand
// clang-format off


#include "cpp4r/declarations.hpp"
#include <R_ext/Visibility.h>

// tvp_exports.h
list tvp_var_estimate(const doubles_matrix<> & y, int L, int training_years, int n_burn, int n_draws, int thinning, int stability_constraint, double lambda_param, int first_diff);
extern "C" SEXP _bp13_tvp_var_estimate(SEXP y, SEXP L, SEXP training_years, SEXP n_burn, SEXP n_draws, SEXP thinning, SEXP stability_constraint, SEXP lambda_param, SEXP first_diff) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(tvp_var_estimate(cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<> &>>(y), cpp4r::as_cpp<cpp4r::decay_t<int>>(L), cpp4r::as_cpp<cpp4r::decay_t<int>>(training_years), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_burn), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_draws), cpp4r::as_cpp<cpp4r::decay_t<int>>(thinning), cpp4r::as_cpp<cpp4r::decay_t<int>>(stability_constraint), cpp4r::as_cpp<cpp4r::decay_t<double>>(lambda_param), cpp4r::as_cpp<cpp4r::decay_t<int>>(first_diff)));
  END_CPP4R
}
// tvp_exports.h
list tvp_var_irfs(const list & tvp_result, const doubles_matrix<> & y, int L, int training_years, int irf_horizon, int n_reps, int h_restrict, int first_diff);
extern "C" SEXP _bp13_tvp_var_irfs(SEXP tvp_result, SEXP y, SEXP L, SEXP training_years, SEXP irf_horizon, SEXP n_reps, SEXP h_restrict, SEXP first_diff) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(tvp_var_irfs(cpp4r::as_cpp<cpp4r::decay_t<const list &>>(tvp_result), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<> &>>(y), cpp4r::as_cpp<cpp4r::decay_t<int>>(L), cpp4r::as_cpp<cpp4r::decay_t<int>>(training_years), cpp4r::as_cpp<cpp4r::decay_t<int>>(irf_horizon), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_reps), cpp4r::as_cpp<cpp4r::decay_t<int>>(h_restrict), cpp4r::as_cpp<cpp4r::decay_t<int>>(first_diff)));
  END_CPP4R
}
// tvp_exports.h
list tvp_var_elasticities(const list & tvp_result, const doubles_matrix<> & y, int L, int training_years, int n_reps, int h_restrict, int first_diff, double upper_supply, double lower_demand);
extern "C" SEXP _bp13_tvp_var_elasticities(SEXP tvp_result, SEXP y, SEXP L, SEXP training_years, SEXP n_reps, SEXP h_restrict, SEXP first_diff, SEXP upper_supply, SEXP lower_demand) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(tvp_var_elasticities(cpp4r::as_cpp<cpp4r::decay_t<const list &>>(tvp_result), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<> &>>(y), cpp4r::as_cpp<cpp4r::decay_t<int>>(L), cpp4r::as_cpp<cpp4r::decay_t<int>>(training_years), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_reps), cpp4r::as_cpp<cpp4r::decay_t<int>>(h_restrict), cpp4r::as_cpp<cpp4r::decay_t<int>>(first_diff), cpp4r::as_cpp<cpp4r::decay_t<double>>(upper_supply), cpp4r::as_cpp<cpp4r::decay_t<double>>(lower_demand)));
  END_CPP4R
}
// tvp_exports.h
list tvp_var_figure2(const list & tvp_result, const doubles_matrix<> & y, int L, int n_reps, int h_restrict, int first_diff, double upper_supply, double lower_demand, int start_period);
extern "C" SEXP _bp13_tvp_var_figure2(SEXP tvp_result, SEXP y, SEXP L, SEXP n_reps, SEXP h_restrict, SEXP first_diff, SEXP upper_supply, SEXP lower_demand, SEXP start_period) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(tvp_var_figure2(cpp4r::as_cpp<cpp4r::decay_t<const list &>>(tvp_result), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<> &>>(y), cpp4r::as_cpp<cpp4r::decay_t<int>>(L), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_reps), cpp4r::as_cpp<cpp4r::decay_t<int>>(h_restrict), cpp4r::as_cpp<cpp4r::decay_t<int>>(first_diff), cpp4r::as_cpp<cpp4r::decay_t<double>>(upper_supply), cpp4r::as_cpp<cpp4r::decay_t<double>>(lower_demand), cpp4r::as_cpp<cpp4r::decay_t<int>>(start_period)));
  END_CPP4R
}
// tvp_exports.h
list tvp_var_figure3(const list & tvp_result, int n_freq, int price_var);
extern "C" SEXP _bp13_tvp_var_figure3(SEXP tvp_result, SEXP n_freq, SEXP price_var) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(tvp_var_figure3(cpp4r::as_cpp<cpp4r::decay_t<const list &>>(tvp_result), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_freq), cpp4r::as_cpp<cpp4r::decay_t<int>>(price_var)));
  END_CPP4R
}
// tvp_exports.h
list tvp_var_figure4(const list & tvp_result, const doubles_matrix<> & y, int L, int n_reps, int h_restrict, int first_diff, double upper_supply, double lower_demand, int start_period);
extern "C" SEXP _bp13_tvp_var_figure4(SEXP tvp_result, SEXP y, SEXP L, SEXP n_reps, SEXP h_restrict, SEXP first_diff, SEXP upper_supply, SEXP lower_demand, SEXP start_period) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(tvp_var_figure4(cpp4r::as_cpp<cpp4r::decay_t<const list &>>(tvp_result), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<> &>>(y), cpp4r::as_cpp<cpp4r::decay_t<int>>(L), cpp4r::as_cpp<cpp4r::decay_t<int>>(n_reps), cpp4r::as_cpp<cpp4r::decay_t<int>>(h_restrict), cpp4r::as_cpp<cpp4r::decay_t<int>>(first_diff), cpp4r::as_cpp<cpp4r::decay_t<double>>(upper_supply), cpp4r::as_cpp<cpp4r::decay_t<double>>(lower_demand), cpp4r::as_cpp<cpp4r::decay_t<int>>(start_period)));
  END_CPP4R
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_bp13_tvp_var_elasticities", (DL_FUNC) &_bp13_tvp_var_elasticities, 9},
    {"_bp13_tvp_var_estimate",     (DL_FUNC) &_bp13_tvp_var_estimate,     9},
    {"_bp13_tvp_var_figure2",      (DL_FUNC) &_bp13_tvp_var_figure2,      9},
    {"_bp13_tvp_var_figure3",      (DL_FUNC) &_bp13_tvp_var_figure3,      3},
    {"_bp13_tvp_var_figure4",      (DL_FUNC) &_bp13_tvp_var_figure4,      9},
    {"_bp13_tvp_var_irfs",         (DL_FUNC) &_bp13_tvp_var_irfs,         8},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_bp13(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
